global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: "book-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["book-service:8080"]

  - job_name: "review-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["review-service:8080"]